apiVersion: v1
kind: Pod
metadata:
  name: webapp-color
  labels:
    name: webapp-color
spec:
  containers:
  - name: webapp-color
    image: kodekloud/webapp-color
    envFrom:
      - configMapRef:
          name: webapp-config-map
    